import * as fs from '../utils/fs'
import * as pathUtils from 'path'

/** Generates the XML contents of the Network Security File. */
const generateConfig = ({
  certificatePath,
}: {
  certificatePath: string | undefined
}) => {
  const certificateBlock = certificatePath
    ? generateCertificateBlock(certificatePath)
    : ''

  return `<?xml version="1.0" encoding="utf-8"?>
  <!-- Intentionally lax Network Security Configuration (generated by apk-mitm) -->
  <network-security-config>
    <!-- Allow cleartext traffic -->
    <base-config cleartextTrafficPermitted="true">
      <trust-anchors>
        <!-- Allow user-added (proxy) certificates -->
        <certificates src="user" />${certificateBlock}
        <certificates src="system" />
      </trust-anchors>
    </base-config>
  </network-security-config>`
}

/** Generates the XML block responsible for registering a custom certificate. */
const generateCertificateBlock = (path: string) => {
  const fileName = pathUtils.basename(path)

  // Android resources are always referred to without their file extension
  const resourceName = fileName.replace(/\.[a-z\d]+$/, '')

  return `\n
        <!-- Allow specific certificate -->
        <certificates src="@raw/${resourceName}" />\n`
}

export default async function createNetworkSecurityConfig(
  path: string,
  { certificatePath }: { certificatePath?: string } = {},
) {
  await fs.mkdir(pathUtils.dirname(path), { recursive: true })

  const config = generateConfig({ certificatePath })
  await fs.writeFile(path, config, 'utf-8')
}
