name: CI
on: push
jobs:
  lint:
    name: Code Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run: yarn
      - name: Check code formatting
        run: yarn lint
  build:
    name: E2E Test / Node.js ${{ matrix.node }}
    strategy:
      matrix:
        node: [10, 14]
      # Prevent one failing job from cancelling the other ones
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: yarn
      - name: Build package
        run: yarn build
      - name: Download example APK
        # Download Telegram FOSS as an example APK
        # (there might be better APKs for testing, I didn't put a lot of thought into picking this one)
        run: wget -O example.apk --no-verbose https://github.com/Telegram-FOSS-Team/Telegram-FOSS/releases/download/v7.0.0/TF-BETA-THERMATK-v7.0.0.apk
      - name: Patch example APK
        run: ./bin/apk-mitm example.apk
